# Crimes in India — Data Filtration & Preparation

---

### Importing required libraries

In [71]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from numpy import random

## Working with Dataset: crimes_in_india_2001_2023

In [3]:
# https://www.kaggle.com/datasets/umeshchandra789/crimes-in-india
# loading the dataset
crimes_in_india = pd.read_csv('Raw Datasets/Crime Datasets/crimes_in_india_2001_2023.csv')

# attribute information:
crimes_in_india.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26690 entries, 0 to 26689
Data columns (total 33 columns):
 #   Column                                               Non-Null Count  Dtype
---  ------                                               --------------  -----
 0   state_ut                                             26690 non-null  object
 1   district                                             26690 non-null  object
 2   year                                                 26690 non-null  int64
 3   murder                                               26690 non-null  int64
 4   attempt_to_murder                                    26690 non-null  int64
 5   culpable_homicide_not_amounting_to_murder            26690 non-null  int64
 6   rape                                                 26690 non-null  int64
 7   custodial_rape                                       26690 non-null  int64
 8   other_rape                                           26690 non-null  int64
 9   kidnapping_and_abduction                             26690 non-null  int64
 10  kidnapping_and_abduction_of_women_and_girls          26690 non-null  int64
 11  kidnapping_and_abduction_of_others                   26690 non-null  int64
 12  dacoity                                              26690 non-null  int64
 13  preparation_and_assembly_for_dacoity                 26690 non-null  int64
 14  robbery                                              26690 non-null  int64
 15  burglary                                             26690 non-null  int64
 16  theft                                                26690 non-null  int64
 17  auto_theft                                           26690 non-null  int64
 18  other_theft                                          26690 non-null  int64
 19  riots                                                26690 non-null  int64
 20  criminal_breach_of_trust                             26690 non-null  int64
 21  cheating                                             26690 non-null  int64
 22  counterfeiting                                       26690 non-null  int64
 23  arson                                                26690 non-null  int64
 24  hurt_grievous_hurt                                   26690 non-null  int64
 25  dowry_deaths                                         26690 non-null  int64
 26  assault_on_women_with_intent_to_outrage_her_modesty  26690 non-null  int64
 27  insult_to_modesty_of_women                           26690 non-null  int64
 28  cruelty_by_husband_or_his_relatives                  26690 non-null  int64
 29  importation_of_girls_from_foreign_countries          26690 non-null  int64
 30  causing_death_by_negligence                          26690 non-null  int64
 31  other_ipc_crimes                                     26690 non-null  int64
 32  total_ipc_crimes                                     26690 non-null  int64
dtypes: int64(31), object(2)
memory usage: 6.7+ MB

In [90]:
crimes_in_india.state_ut.unique()

array(['A & N ISLANDS', 'A&N ISLANDS', 'ANDHRA PRADESH',
       'ARUNACHAL PRADESH', 'ASSAM', 'BIHAR', 'CHANDIGARH',
       'CHHATTISGARH', 'D & N HAVELI', 'D&N HAVELI', 'DAMAN & DIU',
       'DELHI UT', 'GOA', 'GUJARAT', 'HARYANA', 'HIMACHAL PRADESH',
       'JAMMU & KASHMIR', 'JHARKHAND', 'KARNATAKA', 'KERALA',
       'LAKSHADWEEP', 'MADHYA PRADESH', 'MAHARASHTRA', 'MANIPUR',
       'MEGHALAYA', 'MIZORAM', 'NAGALAND', 'ODISHA', 'PUDUCHERRY',
       'PUNJAB', 'RAJASTHAN', 'SIKKIM', 'TAMIL NADU', 'TRIPURA',
       'UTTAR PRADESH', 'UTTARAKHAND', 'WEST BENGAL'], dtype=object)

In [ ]:
crimes_in_india['state_ut'] = (
    crimes_in_india['state_ut']
    .str.upper()
    .str.replace('&', 'AND', regex=False)
    .str.replace(r'\s+', ' ', regex=True)
    .str.strip()
)

In [92]:
# applying precise mapping
state_mapping = {
    'A AND N ISLANDS': 'ANDAMAN AND NICOBAR ISLANDS',
    'D AND N HAVELI': 'DADRA AND NAGAR HAVELI AND DAMAN AND DIU',
    'DAMAN AND DIU': 'DADRA AND NAGAR HAVELI AND DAMAN AND DIU',
    'DELHI UT': 'DELHI',
    'JAMMU AND KASHMIR': 'JAMMU AND KASHMIR'
}

crimes_in_india['state_ut'] = crimes_in_india['state_ut'].replace(state_mapping)

In [95]:
sorted(crimes_in_india['state_ut'].unique())

['AANDN ISLANDS',
 'ANDAMAN AND NICOBAR ISLANDS',
 'ANDHRA PRADESH',
 'ARUNACHAL PRADESH',
 'ASSAM',
 'BIHAR',
 'CHANDIGARH',
 'CHHATTISGARH',
 'DADRA AND NAGAR HAVELI AND DAMAN AND DIU',
 'DANDN HAVELI',
 'DELHI',
 'GOA',
 'GUJARAT',
 'HARYANA',
 'HIMACHAL PRADESH',
 'JAMMU AND KASHMIR',
 'JHARKHAND',
 'KARNATAKA',
 'KERALA',
 'LAKSHADWEEP',
 'MADHYA PRADESH',
 'MAHARASHTRA',
 'MANIPUR',
 'MEGHALAYA',
 'MIZORAM',
 'NAGALAND',
 'ODISHA',
 'PUDUCHERRY',
 'PUNJAB',
 'RAJASTHAN',
 'SIKKIM',
 'TAMIL NADU',
 'TRIPURA',
 'UTTAR PRADESH',
 'UTTARAKHAND',
 'WEST BENGAL']

In [89]:
# printing random 20 records
for i in random.randint(0,500, size = 20):
    print(crimes_in_india.state_ut.loc[i])

ANDHRA PRADESH
ANDHRA PRADESH
ANDHRA PRADESH
A & N ISLANDS
A&N ISLANDS
A & N ISLANDS
ANDHRA PRADESH
ANDHRA PRADESH
ANDHRA PRADESH
ANDHRA PRADESH
A & N ISLANDS
A & N ISLANDS
ANDHRA PRADESH
A & N ISLANDS
ANDHRA PRADESH
ANDHRA PRADESH
ANDHRA PRADESH
A&N ISLANDS
A & N ISLANDS
ANDHRA PRADESH

In [5]:
# A. Standardize Identifiers
crimes_in_india['state_ut'] = crimes_in_india['state_ut'].str.upper().str.strip()
crimes_in_india['destrict'] = crimes_in_india['district'].str.upper().str.strip()

In [6]:
# B. Sort for Time-Series Consistency
crimes_in_india = crimes_in_india.sort_values(['state_ut', 'district', 'year'])

### Violent Crimes

In [ ]:
violent_crimes = [
    'murder',
    'attempt_to_murder',
    'culpable_homicide_not_amounting_to_murder',
    'rape',
    'riots',
    'hurt_grievous_hurt',
    'dowry_deaths',
    'causing_death_by_negligence'
]

### Crimes Against Women

In [ ]:
women_crimes = [
    'rape',
    'custodial_rape',
    'other_rape',
    'kidnapping_and_abduction_of_women_and_girls',
    'dowry_deaths',
    'assault_on_women_with_intent_to_outrage_her_modesty',
    'insult_to_modesty_of_women',
    'cruelty_by_husband_or_his_relatives',
    'importation_of_girls_from_foreign_countries'
]

### Property Crimes

In [ ]:
property_crimes = [
    'dacoity',
    'preparation_and_assembly_for_dacoity',
    'robbery',
    'burglary',
    'theft',
    'auto_theft',
    'other_theft'
]

### Economic / Fraud Crimes

In [10]:
economic_crimes = [
    'criminal_breach_of_trust',
    'cheating',
    'counterfeiting'
]

## Adding Derived Attributes to the DataFrame

In [11]:
crimes_in_india['voilent_crime_total'] = crimes_in_india[violent_crimes].sum(axis=1)
crimes_in_india['women_crime_total'] = crimes_in_india[women_crimes].sum(axis=1)
crimes_in_india['property_crime_total'] = crimes_in_india[property_crimes].sum(axis=1)
crimes_in_india['economic_crime_total'] = crimes_in_india[economic_crimes].sum(axis=1)

In [12]:
# printing updated dataframe information
crimes_in_india.info()

<class 'pandas.core.frame.DataFrame'>
Index: 26690 entries, 0 to 26689
Data columns (total 38 columns):
 #   Column                                               Non-Null Count  Dtype
---  ------                                               --------------  -----
 0   state_ut                                             26690 non-null  object
 1   district                                             26690 non-null  object
 2   year                                                 26690 non-null  int64
 3   murder                                               26690 non-null  int64
 4   attempt_to_murder                                    26690 non-null  int64
 5   culpable_homicide_not_amounting_to_murder            26690 non-null  int64
 6   rape                                                 26690 non-null  int64
 7   custodial_rape                                       26690 non-null  int64
 8   other_rape                                           26690 non-null  int64
 9   kidnapping_and_abduction                             26690 non-null  int64
 10  kidnapping_and_abduction_of_women_and_girls          26690 non-null  int64
 11  kidnapping_and_abduction_of_others                   26690 non-null  int64
 12  dacoity                                              26690 non-null  int64
 13  preparation_and_assembly_for_dacoity                 26690 non-null  int64
 14  robbery                                              26690 non-null  int64
 15  burglary                                             26690 non-null  int64
 16  theft                                                26690 non-null  int64
 17  auto_theft                                           26690 non-null  int64
 18  other_theft                                          26690 non-null  int64
 19  riots                                                26690 non-null  int64
 20  criminal_breach_of_trust                             26690 non-null  int64
 21  cheating                                             26690 non-null  int64
 22  counterfeiting                                       26690 non-null  int64
 23  arson                                                26690 non-null  int64
 24  hurt_grievous_hurt                                   26690 non-null  int64
 25  dowry_deaths                                         26690 non-null  int64
 26  assault_on_women_with_intent_to_outrage_her_modesty  26690 non-null  int64
 27  insult_to_modesty_of_women                           26690 non-null  int64
 28  cruelty_by_husband_or_his_relatives                  26690 non-null  int64
 29  importation_of_girls_from_foreign_countries          26690 non-null  int64
 30  causing_death_by_negligence                          26690 non-null  int64
 31  other_ipc_crimes                                     26690 non-null  int64
 32  total_ipc_crimes                                     26690 non-null  int64
 33  destrict                                             26690 non-null  object
 34  voilent_crime_total                                  26690 non-null  int64
 35  women_crime_total                                    26690 non-null  int64
 36  property_crime_total                                 26690 non-null  int64
 37  economic_crime_total                                 26690 non-null  int64
dtypes: int64(35), object(3)
memory usage: 7.9+ MB

In [13]:
# Exporting the dataframe in New CSV File
crimes_in_india.to_csv('FilteredData/crimes_in_india_2001_2023_filtered.csv')

## SEGREGATED DATAFRAMES

## A. District–Year Level (For Clustering & Hotspots)

In [14]:
district_year_level = crimes_in_india[
    ['state_ut', 'district', 'year',
     'voilent_crime_total',
     'women_crime_total',
     'property_crime_total',
     'economic_crime_total',
     'total_ipc_crimes']
]

# first five records
district_year_level.head()

# K-means clustering, District heatmaps, Crime hotspot analysis k liye kaam ayega!

,state_ut,district,year,voilent_crime_total,women_crime_total,property_crime_total,economic_crime_total,total_ipc_crimes
0,A & N ISLANDS,A and N ISLANDS,2007,159,57,328,31,934
1,A & N ISLANDS,A and N ISLANDS,2014,152,61,333,32,927
2,A & N ISLANDS,A and N ISLANDS,2015,153,60,336,33,959
3,A & N ISLANDS,A and N ISLANDS,2016,151,67,343,38,980
4,A & N ISLANDS,A and N ISLANDS,2017,155,75,346,40,1027

## B. State–Year Aggregated Data

In [15]:
state_year = (
    crimes_in_india.groupby(['state_ut', 'year'], as_index=False)
      .agg({
          'voilent_crime_total': 'sum',
          'women_crime_total': 'sum',
          'property_crime_total': 'sum',
          'economic_crime_total': 'sum',
          'total_ipc_crimes': 'sum'
      })
)

# print first 5 rows
state_year.head()

# Trend analysis (2001–2023), Regression with literacy & employment, Power BI dashboard m kaam ayega

,state_ut,year,voilent_crime_total,women_crime_total,property_crime_total,economic_crime_total,total_ipc_crimes
0,A & N ISLANDS,2001,294,74,396,40,1456
1,A & N ISLANDS,2002,262,58,310,30,1322
2,A & N ISLANDS,2003,314,48,370,32,1416
3,A & N ISLANDS,2004,296,74,556,24,1728
4,A & N ISLANDS,2005,220,52,512,42,1560

## C. Crimes Against Women – Detailed Table

In [16]:
crime_against_women = crimes_in_india[ ['state_ut', 'district', 'year'] + women_crimes]

# printing first 5 rows:
crime_against_women.head()

,state_ut,district,year,rape,custodial_rape,other_rape,kidnapping_and_abduction_of_women_and_girls,dowry_deaths,assault_on_women_with_intent_to_outrage_her_modesty,insult_to_modesty_of_women,cruelty_by_husband_or_his_relatives,importation_of_girls_from_foreign_countries
0,A & N ISLANDS,A and N ISLANDS,2007,3,0,3,9,1,21,2,18,0
1,A & N ISLANDS,A and N ISLANDS,2014,4,0,3,9,0,21,3,19,2
2,A & N ISLANDS,A and N ISLANDS,2015,3,0,2,8,0,22,2,20,3
3,A & N ISLANDS,A and N ISLANDS,2016,2,0,2,9,1,23,3,22,5
4,A & N ISLANDS,A and N ISLANDS,2017,1,1,2,9,1,25,4,25,7

## Exporting Filtered Data in CSV format

In [17]:
state_year.to_csv('FilteredData/crime_state_year.csv')
district_year_level.to_csv('FilteredData/crime_district_year.csv')
crime_against_women.to_csv('FilteredData/crime_against_women.csv')

---

## Working with Dataset : crime_dataset_india_2020-2024.csv

In [18]:
# https://www.kaggle.com/datasets/sudhanvahg/indian-crimes-dataset

# Loading the dataset:
crime_df_2024 = pd.read_csv("Raw Datasets/Crime Datasets/crime_dataset_india_2020-2024.csv")

crime_df_2024.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40160 entries, 0 to 40159
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Report Number       40160 non-null  int64
 1   Date Reported       40160 non-null  object
 2   Date of Occurrence  40160 non-null  object
 3   Time of Occurrence  40160 non-null  object
 4   City                40160 non-null  object
 5   Crime Code          40160 non-null  int64
 6   Crime Description   40160 non-null  object
 7   Victim Age          40160 non-null  int64
 8   Victim Gender       40160 non-null  object
 9   Weapon Used         34370 non-null  object
 10  Crime Domain        40160 non-null  object
 11  Police Deployed     40160 non-null  int64
 12  Case Closed         40160 non-null  object
 13  Date Case Closed    20062 non-null  object
dtypes: int64(4), object(10)
memory usage: 4.3+ MB

In [19]:
# printing first 5 rows
crime_df_2024.head()

,Report Number,Date Reported,Date of Occurrence,Time of Occurrence,City,Crime Code,Crime Description,Victim Age,Victim Gender,Weapon Used,Crime Domain,Police Deployed,Case Closed,Date Case Closed
0,1,02-01-20 0:00,01-01-20 0:00,01-01-20 1:11,Ahmedabad,576,IDENTITY THEFT,16,M,Blunt Object,Violent Crime,13,No,NaN
1,2,01-01-20 19:00,01-01-20 1:00,01-01-20 6:26,Chennai,128,HOMICIDE,37,M,Poison,Other Crime,9,No,NaN
2,3,02-01-20 5:00,01-01-20 2:00,01-01-20 14:30,Ludhiana,271,KIDNAPPING,48,F,Blunt Object,Other Crime,15,No,NaN
3,4,01-01-20 5:00,01-01-20 3:00,01-01-20 14:46,Pune,170,BURGLARY,49,F,Firearm,Other Crime,1,Yes,29-04-20 5:00
4,5,01-01-20 21:00,01-01-20 4:00,01-01-20 16:51,Pune,421,VANDALISM,30,F,Other,Other Crime,18,Yes,08-01-20 21:00

### Cleaning The Dataset

In [20]:
# renaming the columns for clean code
crime_df_2024.columns = crime_df_2024.columns.str.lower().str.replace(' ', '_')

#printing first 2 records
crime_df_2024.head(2)

,report_number,date_reported,date_of_occurrence,time_of_occurrence,city,crime_code,crime_description,victim_age,victim_gender,weapon_used,crime_domain,police_deployed,case_closed,date_case_closed
0,1,02-01-20 0:00,01-01-20 0:00,01-01-20 1:11,Ahmedabad,576,IDENTITY THEFT,16,M,Blunt Object,Violent Crime,13,No,NaN
1,2,01-01-20 19:00,01-01-20 1:00,01-01-20 6:26,Chennai,128,HOMICIDE,37,M,Poison,Other Crime,9,No,NaN

In [21]:
date_cols = ['date_reported', 'date_of_occurrence', 'date_case_closed']
for col in date_cols:
    crime_df_2024[col] = pd.to_datetime(crime_df_2024[col], errors='coerce')

crime_df_2024.info()

C:\Users\sagar\AppData\Local\Temp\ipykernel_25268\4269863786.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  crime_df_2024[col] = pd.to_datetime(crime_df_2024[col], errors='coerce')
C:\Users\sagar\AppData\Local\Temp\ipykernel_25268\4269863786.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  crime_df_2024[col] = pd.to_datetime(crime_df_2024[col], errors='coerce')
C:\Users\sagar\AppData\Local\Temp\ipykernel_25268\4269863786.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  crime_df_2024[col] = pd.to_datetime(crime_df_2024[col], errors='coerce')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40160 entries, 0 to 40159
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   report_number       40160 non-null  int64
 1   date_reported       40160 non-null  datetime64[ns]
 2   date_of_occurrence  40160 non-null  datetime64[ns]
 3   time_of_occurrence  40160 non-null  object
 4   city                40160 non-null  object
 5   crime_code          40160 non-null  int64
 6   crime_description   40160 non-null  object
 7   victim_age          40160 non-null  int64
 8   victim_gender       40160 non-null  object
 9   weapon_used         34370 non-null  object
 10  crime_domain        40160 non-null  object
 11  police_deployed     40160 non-null  int64
 12  case_closed         40160 non-null  object
 13  date_case_closed    20062 non-null  datetime64[ns]
dtypes: datetime64[ns](3), int64(4), object(7)
memory usage: 4.3+ MB

In [22]:
# checking the date time format
crime_df_2024.date_reported.head(10)

0   2020-02-01 00:00:00
1   2020-01-01 19:00:00
2   2020-02-01 05:00:00
3   2020-01-01 05:00:00
4   2020-01-01 21:00:00
5   2020-02-01 03:00:00
6   2020-01-01 16:00:00
7   2020-02-01 10:00:00
8   2020-04-01 03:00:00
9   2020-03-01 07:00:00
Name: date_reported, dtype: datetime64[ns]

In [23]:
# checking for NaN values:
crime_df_2024.isna().sum()

report_number             0
date_reported             0
date_of_occurrence        0
time_of_occurrence        0
city                      0
crime_code                0
crime_description         0
victim_age                0
victim_gender             0
weapon_used            5790
crime_domain              0
police_deployed           0
case_closed               0
date_case_closed      20098
dtype: int64

In [24]:
# filling NaN value for attribute: weapon_used -> UNKNOWN
crime_df_2024['weapon_used'] = crime_df_2024['weapon_used'].fillna('UNKNOWN')

## DERIVED COLUMNS

### A. Case Status (Binary)

In [25]:
crime_df_2024['case_closed_flag'] = crime_df_2024['case_closed'].map({
    'Yes': 1,
    'No': 0
})

# Yes matlab 1 and No matlab 0 simple

### B. Case Resolution Time

In [26]:
crime_df_2024['case_resolution_days'] = (
    crime_df_2024['date_case_closed'] - crime_df_2024['date_reported']
).dt.days

crime_df_2024.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40160 entries, 0 to 40159
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   report_number         40160 non-null  int64
 1   date_reported         40160 non-null  datetime64[ns]
 2   date_of_occurrence    40160 non-null  datetime64[ns]
 3   time_of_occurrence    40160 non-null  object
 4   city                  40160 non-null  object
 5   crime_code            40160 non-null  int64
 6   crime_description     40160 non-null  object
 7   victim_age            40160 non-null  int64
 8   victim_gender         40160 non-null  object
 9   weapon_used           40160 non-null  object
 10  crime_domain          40160 non-null  object
 11  police_deployed       40160 non-null  int64
 12  case_closed           40160 non-null  object
 13  date_case_closed      20062 non-null  datetime64[ns]
 14  case_closed_flag      40160 non-null  int64
 15  case_resolution_days  20062 non-null  float64
dtypes: datetime64[ns](3), float64(1), int64(5), object(7)
memory usage: 4.9+ MB

In [27]:
# total NaN value in case_resolution_days
crime_df_2024.case_resolution_days.isna().sum()

# here NaN reflect because case is not closed!
# # # # baad me dekhunga...

np.int64(20098)

### C. Victim Age Grouping

In [28]:
crime_df_2024['victim_age_group'] = pd.cut(
    crime_df_2024['victim_age'],
    bins=[0, 17, 30, 45, 60, 100],
    labels=['Minor', 'Young Adult', 'Adult', 'Middle Aged', 'Senior']
)

# | Age Range | Group       |
# | --------- | ----------- |
# | 0 – 17    | Minor       |
# | 18 – 30   | Young Adult |
# | 31 – 45   | Adult       |
# | 46 – 60   | Middle Aged |
# | 61 – 100  | Senior      |

crime_df_2024.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40160 entries, 0 to 40159
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   report_number         40160 non-null  int64
 1   date_reported         40160 non-null  datetime64[ns]
 2   date_of_occurrence    40160 non-null  datetime64[ns]
 3   time_of_occurrence    40160 non-null  object
 4   city                  40160 non-null  object
 5   crime_code            40160 non-null  int64
 6   crime_description     40160 non-null  object
 7   victim_age            40160 non-null  int64
 8   victim_gender         40160 non-null  object
 9   weapon_used           40160 non-null  object
 10  crime_domain          40160 non-null  object
 11  police_deployed       40160 non-null  int64
 12  case_closed           40160 non-null  object
 13  date_case_closed      20062 non-null  datetime64[ns]
 14  case_closed_flag      40160 non-null  int64
 15  case_resolution_days  20062 non-null  float64
 16  victim_age_group      40160 non-null  category
dtypes: category(1), datetime64[ns](3), float64(1), int64(5), object(7)
memory usage: 4.9+ MB

## FILTERED DATAFRAMES

### Export Updated DataFrame to CSV

In [29]:
crime_df_2024.to_csv('FilteredData/2020_to_2024/crime_reports_2020_2024.csv')

### Clean Master Incident Table

In [30]:
normalized_crime_reports_2020_2024 = crime_df_2024[
    ['report_number', 'date_reported', 'date_of_occurrence',
     'city', 'crime_domain', 'crime_description',
     'victim_age', 'victim_age_group', 'victim_gender',
     'weapon_used', 'police_deployed',
     'case_closed_flag', 'case_resolution_days']
]
normalized_crime_reports_2020_2024.head(10)

,report_number,date_reported,date_of_occurrence,city,crime_domain,crime_description,victim_age,victim_age_group,victim_gender,weapon_used,police_deployed,case_closed_flag,case_resolution_days
0,1,2020-02-01 00:00:00,2020-01-01 00:00:00,Ahmedabad,Violent Crime,IDENTITY THEFT,16,Minor,M,Blunt Object,13,0,NaN
1,2,2020-01-01 19:00:00,2020-01-01 01:00:00,Chennai,Other Crime,HOMICIDE,37,Adult,M,Poison,9,0,NaN
2,3,2020-02-01 05:00:00,2020-01-01 02:00:00,Ludhiana,Other Crime,KIDNAPPING,48,Middle Aged,F,Blunt Object,15,0,NaN
3,4,2020-01-01 05:00:00,2020-01-01 03:00:00,Pune,Other Crime,BURGLARY,49,Middle Aged,F,Firearm,1,1,119.0
4,5,2020-01-01 21:00:00,2020-01-01 04:00:00,Pune,Other Crime,VANDALISM,30,Young Adult,F,Other,18,1,213.0
5,6,2020-02-01 03:00:00,2020-01-01 05:00:00,Delhi,Violent Crime,ASSAULT,16,Minor,M,Firearm,18,1,58.0
6,7,2020-01-01 16:00:00,2020-01-01 06:00:00,Chennai,Violent Crime,VEHICLE - STOLEN,64,Senior,F,Knife,13,1,83.0
7,8,2020-02-01 10:00:00,2020-01-01 07:00:00,Chennai,Other Crime,COUNTERFEITING,78,Senior,X,Knife,8,0,NaN
8,9,2020-04-01 03:00:00,2020-01-01 08:00:00,Mumbai,Other Crime,EXTORTION,41,Adult,X,Blunt Object,1,0,NaN
9,10,2020-03-01 07:00:00,2020-01-01 09:00:00,Chennai,Other Crime,PUBLIC INTOXICATION,29,Young Adult,M,Knife,4,0,NaN

In [31]:
# exporting to CSV file
normalized_crime_reports_2020_2024.to_csv('FilteredData/2020_to_2024/normalized_crime_reports_2020_2024.csv')

# i will use this in EDA, Bi Dashboard and case outcome analysis

### B. Crimes Against Women (Incident-Level)

In [32]:
df_women_incidents = crime_df_2024[
    crime_df_2024['victim_gender'] == 'F'
]

df_women_incidents.to_csv('FilteredData/2020_to_2024/crime_against_women_2020_2024.csv')

In [33]:
df_women_incidents.head()

# ------ i will use this in Gender-focused justice analysis and Case closure comparison ---------

,report_number,date_reported,date_of_occurrence,time_of_occurrence,city,crime_code,crime_description,victim_age,victim_gender,weapon_used,crime_domain,police_deployed,case_closed,date_case_closed,case_closed_flag,case_resolution_days,victim_age_group
2,3,2020-02-01 05:00:00,2020-01-01 02:00:00,01-01-20 14:30,Ludhiana,271,KIDNAPPING,48,F,Blunt Object,Other Crime,15,No,NaT,0,NaN,Middle Aged
3,4,2020-01-01 05:00:00,2020-01-01 03:00:00,01-01-20 14:46,Pune,170,BURGLARY,49,F,Firearm,Other Crime,1,Yes,2020-04-29 05:00:00,1,119.0,Middle Aged
4,5,2020-01-01 21:00:00,2020-01-01 04:00:00,01-01-20 16:51,Pune,421,VANDALISM,30,F,Other,Other Crime,18,Yes,2020-08-01 21:00:00,1,213.0,Young Adult
6,7,2020-01-01 16:00:00,2020-01-01 06:00:00,01-01-20 14:08,Chennai,172,VEHICLE - STOLEN,64,F,Knife,Violent Crime,13,Yes,2020-03-24 16:00:00,1,83.0,Senior
12,13,2020-01-01 16:00:00,2020-01-01 12:00:00,01-01-20 23:14,Visakhapatnam,498,FRAUD,36,F,Poison,Other Crime,3,Yes,2020-02-29 16:00:00,1,59.0,Adult

### C. Weapon-Based Crime Analysis

In [34]:
df_weapon_crimes = crime_df_2024.groupby('weapon_used', as_index=False).agg(total_cases=('report_number', 'count'))

df_weapon_crimes.head(10)

    weapon_used  total_cases
0  Blunt Object         5737
1    Explosives         5751
2       Firearm         5643
3         Knife         5835
4         Other         5676
5        Poison         5728
6       UNKNOWN         5790

In [35]:
df_weapon_crimes.to_csv('FilteredData/2020_to_2024/weapon_based_crime_2020_2024.csv')

### D. Police Response Effectiveness

In [36]:
df_police_effect = crime_df_2024.groupby('police_deployed', as_index=False).agg(total_cases=('report_number', 'count'), closure_rate=('case_closed_flag', 'mean'))

df_police_effect.head()

   police_deployed  total_cases  closure_rate
0                1         2088      0.491858
1                2         2153      0.499303
2                3         2119      0.506843
3                4         2063      0.490548
4                5         2065      0.503632

In [37]:
# exporting to another csv file
df_police_effect.to_csv('FilteredData/2020_to_2024/Police_Response_Effectiveness_2020-2024.csv')

---

## Working with Dataset: NCRB_Table_1A.1

#### State/UT-wise Number of Indian Penal Code (IPC) Crimes from 2020 to 2022 - NCRB_Table_1A.1

In [38]:
# https://www.data.gov.in/resource/stateut-wise-number-indian-penal-code-ipc-crimes-2020-2022

# Loading the dataset:
ncrb_table_ipc_crimes = pd.read_csv('Raw Datasets/Crime Datasets/NCRB_Table_1A.1.csv')

# checking the attributes
ncrb_table_ipc_crimes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 8 columns):
 #   Column                                           Non-Null Count  Dtype
---  ------                                           --------------  -----
 0   Sl. No.                                          36 non-null     int64
 1   State/UT                                         36 non-null     object
 2   2020                                             36 non-null     int64
 3   2021                                             36 non-null     int64
 4   2022                                             36 non-null     int64
 5   Mid-Year Projected Population (in Lakhs) (2022)  36 non-null     float64
 6   Rate of Cognizable Crimes (IPC) (2022)           36 non-null     float64
 7   Chargesheeting Rate (2022)                       36 non-null     float64
dtypes: float64(3), int64(4), object(1)
memory usage: 2.4+ KB

### Cleaning the Dataset

In [39]:
ncrb = ncrb_table_ipc_crimes.copy()

ncrb.columns = [
    'sl_no',
    'state_ut',
    'crimes_2020',
    'crimes_2021',
    'crimes_2022',
    'population_lakhs_2022',
    'crime_rate_2022',
    'chargesheeting_rate_2022'
]

# transform strings:
ncrb['state_ut'] = ncrb['state_ut'].str.upper().str.strip()

### A. Year-on-Year Growth (2020–2022)

In [40]:
# [(cy - py) / py]x 100

ncrb['growth_20_21_pct'] = (
    (ncrb['crimes_2021'] - ncrb['crimes_2020']) / ncrb['crimes_2020']
) * 100

ncrb['growth_21_22_pct'] = (
    (ncrb['crimes_2022'] - ncrb['crimes_2021']) / ncrb['crimes_2021']
) * 100

### B. Average Crime Volume

In [41]:
ncrb['avg_crimes_2020_22'] = ncrb[['crimes_2020','crimes_2021','crimes_2022']].mean(axis=1)

### C. Crimes per Million Population

In [42]:
# lakh -> million (1m = 10 Lakh)
ncrb['population_million_2022'] = ncrb['population_lakhs_2022'] / 10


# per million = total crimes / population
ncrb['crime_per_million_2022'] = (
    ncrb['crimes_2022'] / ncrb['population_million_2022']
)

In [43]:
ncrb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   sl_no                     36 non-null     int64
 1   state_ut                  36 non-null     object
 2   crimes_2020               36 non-null     int64
 3   crimes_2021               36 non-null     int64
 4   crimes_2022               36 non-null     int64
 5   population_lakhs_2022     36 non-null     float64
 6   crime_rate_2022           36 non-null     float64
 7   chargesheeting_rate_2022  36 non-null     float64
 8   growth_20_21_pct          36 non-null     float64
 9   growth_21_22_pct          36 non-null     float64
 10  avg_crimes_2020_22        36 non-null     float64
 11  population_million_2022   36 non-null     float64
 12  crime_per_million_2022    36 non-null     float64
dtypes: float64(8), int64(4), object(1)
memory usage: 3.8+ KB

In [44]:
# PowerBi => Crime vs Population, Large states vs small states, Raw crimes vs crime rate, Crime vs Justice Efficiency, Does high crime → low chargesheeting?, Are low-crime states more efficient?,  Post-COVID Trend, Which states saw spike after 2020?

In [45]:
## Remainder: agar jarurat padi toH: 
# merge with df_state_2022
# df_state_2022 = df_state_year[df_state_year['year'] == 2022]

# df_state_2022 = df_state_2022.merge(
#     ncrb,
#     on='state_ut',
#     how='left'
# )

### Exporting data

In [46]:
ncrb.to_csv("FilteredData/ncrb_state_wise_ipc_summary_2020_2022.csv")

## Working with Crime Judgement Analysis

## Loading Data:

In [47]:
# https://njdg.ecourts.gov.in/njdg_v3/

judge_count = pd.read_excel("Raw Datasets/Crime Datasets/court_judge_count_report 2025.xlsx")

judge_count.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37 entries, 0 to 36
Data columns (total 9 columns):
 #   Column                                                                      Non-Null Count  Dtype
---  ------                                                                      --------------  -----
 0   Sr No                                                                       37 non-null     int64
 1   State Name                                                                  37 non-null     object
 2   Presiding Officers/Judges  (A)                                              37 non-null     int64
 3   Incharge Courts (B)                                                         37 non-null     int64
 4   Link Courts ©                                                               37 non-null     int64
 5   Total Courts (A+B+C)                                                        37 non-null     int64
 6   Empty Courts                                                                37 non-null     int64
 7   Invalid JOCode Count                                                        37 non-null     int64
 8   Courts Closed But Cases but cases are pending  [Total Courts(no of cases)]  37 non-null     object
dtypes: int64(7), object(2)
memory usage: 2.7+ KB

| Column                          | Meaning                         |
| ------------------------------- | ------------------------------- |
| Presiding Officers / Judges (A) | Actual working judges           |
| Incharge Courts (B)             | Courts without permanent judges |
| Link Courts (C)                 | Courts managed temporarily      |
| Total Courts (A+B+C)            | Total sanctioned courts         |
| Empty Courts                    | Vacant courts                   |
| Invalid JOCode Count            | Data quality / admin issues     |
| Courts Closed but cases pending | Backlog indicator               |

### A. Rename Columns for readability

In [48]:
judges = judge_count.copy()

judges.columns = [
    'sr_no',
    'state_ut',
    'working_judges',
    'incharge_courts',
    'link_courts',
    'total_courts',
    'empty_courts',
    'invalid_jocode_count',
    'courts_closed_cases_pending'
]

### B. Cleaning State Names

In [49]:
judges['state_ut'] = judges['state_ut'].str.upper().str.strip()

In [50]:
judges.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37 entries, 0 to 36
Data columns (total 9 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   sr_no                        37 non-null     int64
 1   state_ut                     37 non-null     object
 2   working_judges               37 non-null     int64
 3   incharge_courts              37 non-null     int64
 4   link_courts                  37 non-null     int64
 5   total_courts                 37 non-null     int64
 6   empty_courts                 37 non-null     int64
 7   invalid_jocode_count         37 non-null     int64
 8   courts_closed_cases_pending  37 non-null     object
dtypes: int64(7), object(2)
memory usage: 2.7+ KB

In [51]:
# judges['pending_cases_in_closed_courts'] = (
#     judges['courts_closed_cases_pending']
#     .str.extract(r'(\d+)')
#     .astype(float)
# )

In [52]:
judges.head()

,sr_no,state_ut,working_judges,incharge_courts,link_courts,total_courts,empty_courts,invalid_jocode_count,courts_closed_cases_pending
0,1,ANDAMAN AND NICOBAR,9,0,0,9,12,7,0
1,2,ANDHRA PRADESH,529,114,4,647,657,1,2 (3 )
2,3,ARUNACHAL PRADESH,15,3,1,19,15,0,4 (33 )
3,4,ASSAM,375,27,1,403,527,0,2 (10 )
4,5,BIHAR,1450,618,2,2070,3053,0,87 (1605 )

## Derived Metric

### A. Court Vacancy Rate

In [53]:
# Indicate justice delays.
judges['court_vacancy_rate_pct'] = (
    judges['empty_courts'] / judges['total_courts']
) * 100

### B. Judges per Court

In [54]:
judges['judges_per_court'] = (
    judges['working_judges'] / judges['total_courts']
)

### C. Temporary Dependency Ratio

In [55]:
# TCR = [n(inchageCourts) + n(linkCourts)]/n(totalCourts)
judges['temporary_court_ratio_pct'] = (
    (judges['incharge_courts'] + judges['link_courts']) / judges['total_courts']
) * 100

In [56]:
judges.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37 entries, 0 to 36
Data columns (total 12 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   sr_no                        37 non-null     int64
 1   state_ut                     37 non-null     object
 2   working_judges               37 non-null     int64
 3   incharge_courts              37 non-null     int64
 4   link_courts                  37 non-null     int64
 5   total_courts                 37 non-null     int64
 6   empty_courts                 37 non-null     int64
 7   invalid_jocode_count         37 non-null     int64
 8   courts_closed_cases_pending  37 non-null     object
 9   court_vacancy_rate_pct       36 non-null     float64
 10  judges_per_court             36 non-null     float64
 11  temporary_court_ratio_pct    36 non-null     float64
dtypes: float64(3), int64(7), object(2)
memory usage: 3.6+ KB

#### Export dataFrame

In [57]:
judges.to_csv('FilteredData/courts_judge_count_report_2025.csv')

#### Questions:

In [58]:
# 1. Crime Rate vs Court Vacancy Rate
# “Are high-crime states also under-staffed judicially?”

# 2. Chargesheeting Rate vs Judges per Court
# “Does judicial capacity affect case completion?”

# 3. Crime Growth vs Justice Capacity
# “Did post-2020 crime growth outpace judicial expansion?”

---

### Loading dataset: Summary_Report_on_Courts_2025

In [59]:
# https://njdg.ecourts.gov.in/njdg_v3/ 
summary_report_on_courts = pd.read_excel("Raw Datasets/Crime Datasets/Summary_Report_on_Courts_2025.xlsx")

summary_report_on_courts.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 8 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Sr No                                   36 non-null     int64
 1   State                                   36 non-null     object
 2   Total Districts                         36 non-null     int64
 3   Total Court Complexes                   36 non-null     int64
 4   Total Establishments                    36 non-null     int64
 5   Total Cases in DB (Pending + Disposed)  36 non-null     int64
 6   Total Orders                            36 non-null     int64
 7   Orders Not Uploaded                     36 non-null     int64
dtypes: int64(7), object(1)
memory usage: 2.4+ KB

| Column                | Column Information               |
| --------------------- | -------------------------------- |
| Total Districts       | Administrative spread            |
| Total Court Complexes | Physical infrastructure          |
| Total Establishments  | Functional courts                |
| Total Cases in DB     | Case burden (pending + disposed) |
| Total Orders          | Judicial output                  |
| Orders Not Uploaded   | Digital inefficiency             |

## Cleaning & Standardization

### A. Rename Columns

In [60]:
courts = summary_report_on_courts.copy()

courts.columns = [
    'sr_no',
    'state_ut',
    'total_districts',
    'court_complexes',
    'total_establishments',
    'total_cases_db',
    'total_orders',
    'orders_not_uploaded'
]

### B. Normalize State Names

In [61]:
courts['state_ut'] = courts['state_ut'].str.upper().str.strip()

## High-Impact Derived Metrics

### A. Case Load per Establishment

In [62]:
# pressure per court = total case / total establishment

courts['cases_per_establishment'] = (
    courts['total_cases_db'] / courts['total_establishments']
)

### B. Orders per Establishment

In [63]:
# productivity = total orders / establishment

courts['orders_per_establishment'] = (
    courts['total_orders'] / courts['total_establishments']
)

### C. Digital Efficiency Gap (% Orders Not Uploaded)

In [64]:
# useful for e-governance analysis

courts['orders_not_uploaded_pct'] = (
    courts['orders_not_uploaded'] / courts['total_orders']
) * 100

### D. Cases per District (Regional Load)

In [65]:
# total cases / no of disticts

courts['cases_per_district'] = (
    courts['total_cases_db'] / courts['total_districts']
)

## Merge with Judge Infrastructure

In [66]:
justice_capacity = judges.merge(
    courts,
    on='state_ut',
    how='inner'
)
justice_capacity.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 23 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   sr_no_x                      36 non-null     int64
 1   state_ut                     36 non-null     object
 2   working_judges               36 non-null     int64
 3   incharge_courts              36 non-null     int64
 4   link_courts                  36 non-null     int64
 5   total_courts                 36 non-null     int64
 6   empty_courts                 36 non-null     int64
 7   invalid_jocode_count         36 non-null     int64
 8   courts_closed_cases_pending  36 non-null     object
 9   court_vacancy_rate_pct       36 non-null     float64
 10  judges_per_court             36 non-null     float64
 11  temporary_court_ratio_pct    36 non-null     float64
 12  sr_no_y                      36 non-null     int64
 13  total_districts              36 non-null     int64
 14  court_complexes              36 non-null     int64
 15  total_establishments         36 non-null     int64
 16  total_cases_db               36 non-null     int64
 17  total_orders                 36 non-null     int64
 18  orders_not_uploaded          36 non-null     int64
 19  cases_per_establishment      36 non-null     float64
 20  orders_per_establishment     36 non-null     float64
 21  orders_not_uploaded_pct      36 non-null     float64
 22  cases_per_district           36 non-null     float64
dtypes: float64(7), int64(14), object(2)
memory usage: 6.6+ KB

In [67]:
# export 
justice_capacity.to_csv('FilteredData/justice_capacity_in_India_2025.csv')

In [68]:
# Merge with NCRB Crime Summary (optional because of old data vs new data)
justice_crime = justice_capacity.merge(
    ncrb_table_ipc_crimes,
    left_on='state_ut',
    right_on='State/UT',
    how='inner'
)

justice_crime.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Data columns (total 31 columns):
 #   Column                                           Non-Null Count  Dtype
---  ------                                           --------------  -----
 0   sr_no_x                                          0 non-null      int64
 1   state_ut                                         0 non-null      object
 2   working_judges                                   0 non-null      int64
 3   incharge_courts                                  0 non-null      int64
 4   link_courts                                      0 non-null      int64
 5   total_courts                                     0 non-null      int64
 6   empty_courts                                     0 non-null      int64
 7   invalid_jocode_count                             0 non-null      int64
 8   courts_closed_cases_pending                      0 non-null      object
 9   court_vacancy_rate_pct                           0 non-null      float64
 10  judges_per_court                                 0 non-null      float64
 11  temporary_court_ratio_pct                        0 non-null      float64
 12  sr_no_y                                          0 non-null      int64
 13  total_districts                                  0 non-null      int64
 14  court_complexes                                  0 non-null      int64
 15  total_establishments                             0 non-null      int64
 16  total_cases_db                                   0 non-null      int64
 17  total_orders                                     0 non-null      int64
 18  orders_not_uploaded                              0 non-null      int64
 19  cases_per_establishment                          0 non-null      float64
 20  orders_per_establishment                         0 non-null      float64
 21  orders_not_uploaded_pct                          0 non-null      float64
 22  cases_per_district                               0 non-null      float64
 23  Sl. No.                                          0 non-null      int64
 24  State/UT                                         0 non-null      object
 25  2020                                             0 non-null      int64
 26  2021                                             0 non-null      int64
 27  2022                                             0 non-null      int64
 28  Mid-Year Projected Population (in Lakhs) (2022)  0 non-null      float64
 29  Rate of Cognizable Crimes (IPC) (2022)           0 non-null      float64
 30  Chargesheeting Rate (2022)                       0 non-null      float64
dtypes: float64(10), int64(18), object(3)
memory usage: 132.0+ bytes