# MONTH WISE CRIME RECORDS IN INDIA 2025 - DATA ANALYTICS

#### Source: https://www.data.gov.in/catalog/crime-reveiw-year-2025?page=2

#### Importing Required Libraries

In [87]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import math
import os
import datetime
import statistics as stat

### Loading: January 2025 datafile.csv

In [88]:
jan_2025 = pd.read_csv('Raw Datasets/Crime Datasets/CRIME REVIEW FOR YEAR 2025/JANUARY 2025 datafile.csv')

jan_2025.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 729 entries, 0 to 728
Data columns (total 8 columns):
 #   Column                                                      Non-Null Count  Dtype
---  ------                                                      --------------  -----
 0   SL NO                                                       729 non-null    int64
 1   HEADS CRIME                                                 729 non-null    object
 2   MAJOR HEADS                                                 729 non-null    object
 3   MINOR HEADS                                                 660 non-null    object
 4   During the current year upto the end of month under review  724 non-null    float64
 5   During the corresponding month of previous year             724 non-null    float64
 6   During the previous month                                   724 non-null    float64
 7   During the current month                                    723 non-null    float64
dtypes: float64(4), int64(1), object(3)
memory usage: 45.7+ KB

| Column                            | Meaning                                         |
| --------------------------------- | ----------------------------------------------- |
| HEADS CRIME                       | Broad crime category (IPC / SLL / Special Acts) |
| MAJOR HEADS                       | Major crime classification                      |
| MINOR HEADS                       | Specific crime types                            |
| Current year upto end of month    | YTD cumulative (Jan–Apr 2025)                   |
| Corresponding month previous year | YTD comparison (Jan–Apr 2024)                   |
| During previous month             | March 2025                                      |
| During current month              | April 2025                                      |

In [89]:
jan_2025.head()

,SL NO,HEADS CRIME,MAJOR HEADS,MINOR HEADS,During the current year upto the end of month under review,During the corresponding month of previous year,During the previous month,During the current month
0,1,A - IPC Crime,"Murder (Sec.302/303 IPC/103,104 BNS)",For gain,4.0,3.0,7.0,4.0
1,2,A - IPC Crime,"Murder (Sec.302/303 IPC/103,104 BNS)",Over Property Dispute,2.0,2.0,2.0,2.0
2,3,A - IPC Crime,"Murder (Sec.302/303 IPC/103,104 BNS)",Due to Personal Vendetta or enemity,2.0,1.0,2.0,2.0
3,4,A - IPC Crime,"Murder (Sec.302/303 IPC/103,104 BNS)",Due to Sexual jealousy,2.0,1.0,2.0,2.0
4,5,A - IPC Crime,"Murder (Sec.302/303 IPC/103,104 BNS)",For dowry by burning,0.0,0.0,0.0,0.0

#### A. Rename Columns

In [90]:
jan = jan_2025.copy()

jan.columns = [
    'sl_no',
    'crime_head',
    'major_head',
    'minor_head',
    'ytd_current_year',
    'ytd_previous_year',
    'previous_month',
    'current_month'
]

#### B. Handle Missing Values

In [91]:
jan['minor_head'] = jan['minor_head'].fillna('ALL / NOT SPECIFIED')

##### For numeric values

In [92]:
numeric_cols = [
    'ytd_current_year',
    'ytd_previous_year',
    'previous_month',
    'current_month'
]

jan[numeric_cols] = jan[numeric_cols].fillna(0)

### High-Value Derived Metrics

#### A. Month-on-Month Growth (%)

In [93]:
# # growth % = [current month - prev. month] / prev. month] * 100 
# # Shows crime spikes or declines

# jan['mom_growth_pct'] = (
#     (jan['current_month'] - jan['previous_month'])
#     / jan['previous_month'].replace(0, pd.NA)
# ) * 100

#### B. Year-on-Year Growth (YTD)

In [94]:
# # year on year growth % = (cy-py /py )*100
# # indicator for policy evaluation

# jan['yoy_ytd_growth_pct'] = (
#     (jan['ytd_current_year'] - jan['ytd_previous_year'])
#     / jan['ytd_previous_year'].replace(0, pd.NA)
# ) * 100

### Loading: Feb 2025 datafile.csv

In [95]:
feb_2025 = pd.read_csv('Raw Datasets/Crime Datasets/CRIME REVIEW FOR YEAR 2025/FEB 2025 datafile.csv')

feb_2025.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 730 entries, 0 to 729
Data columns (total 8 columns):
 #   Column                                                      Non-Null Count  Dtype
---  ------                                                      --------------  -----
 0   SL.NO.                                                      730 non-null    int64
 1   HEAD CRIMES                                                 730 non-null    object
 2   MAJOR HEADS                                                 730 non-null    object
 3   MINOR HEADS                                                 688 non-null    object
 4   During the current year upto the end of month under review  725 non-null    float64
 5   During the corresponding month of previous year             725 non-null    float64
 6   During the previous month                                   725 non-null    float64
 7   During the current month                                    725 non-null    float64
dtypes: float64(4), int64(1), object(3)
memory usage: 45.8+ KB

In [96]:
feb_2025.head()

,SL.NO.,HEAD CRIMES,MAJOR HEADS,MINOR HEADS,During the current year upto the end of month under review,During the corresponding month of previous year,During the previous month,During the current month
0,1,A - IPC Crime,"Murder (Sec.302/303 IPC/103,104 BNS)",For gain,7.0,2.0,4.0,3.0
1,2,A - IPC Crime,"Murder (Sec.302/303 IPC/103,104 BNS)",Over Property Dispute,6.0,6.0,2.0,4.0
2,3,A - IPC Crime,"Murder (Sec.302/303 IPC/103,104 BNS)",Due to Personal Vendetta or enemity,7.0,1.0,2.0,5.0
3,4,A - IPC Crime,"Murder (Sec.302/303 IPC/103,104 BNS)",Due to Sexual jealousy,6.0,1.0,2.0,4.0
4,5,A - IPC Crime,"Murder (Sec.302/303 IPC/103,104 BNS)",For dowry by burning,1.0,0.0,1.0,0.0

#### Standardize Column Names

In [97]:
feb = feb_2025.copy()

feb.columns = [
    'sl_no',
    'crime_head',
    'major_head',
    'minor_head',
    'ytd_current_year',
    'ytd_previous_year',
    'previous_month',
    'current_month'
]

#### Clean Missing Values

In [98]:
feb['minor_head'] = feb['minor_head'].fillna('ALL / NOT SPECIFIED')

numeric_cols = [
    'ytd_current_year',
    'ytd_previous_year',
    'previous_month',
    'current_month'
]

feb[numeric_cols] = feb[numeric_cols].fillna(0)

#### Month Identifier (for joining the data)

In [99]:
feb['month'] = '2025-02'
jan['month'] = '2025-01'

In [100]:
# Combine Monthly Datasets 
# monthly_crime = pd.concat(
#     [feb, april],
#     ignore_index=True
# )

### Loading: MARCH 2025 datafile.csv

In [101]:
march_2025 = pd.read_csv('Raw Datasets/Crime Datasets/CRIME REVIEW FOR YEAR 2025/MARCH 2025 datafile.csv')

march_2025.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 729 entries, 0 to 728
Data columns (total 9 columns):
 #   Column                                                      Non-Null Count  Dtype
---  ------                                                      --------------  -----
 0   Sl.No.                                                      729 non-null    int64
 1   Heads of Crime                                              729 non-null    object
 2   Major Heads                                                 729 non-null    object
 3   Minor Heads                                                 659 non-null    object
 4   During the current year upto the end of month under review  729 non-null    int64
 5   During the corresponding month of previous year             729 non-null    int64
 6   During the previous month                                   729 non-null    int64
 7   During the current month                                    729 non-null    int64
 8   Unnamed: 8                                                  3 non-null      float64
dtypes: float64(1), int64(5), object(3)
memory usage: 51.4+ KB

In [102]:
march_2025.head()

,Sl.No.,Heads of Crime,Major Heads,Minor Heads,During the current year upto the end of month under review,During the corresponding month of previous year,During the previous month,During the current month,Unnamed: 8
0,1,A - IPC Crime,"Murder (Sec.302/303 IPC/103,104 BNS)",For gain,9,2,3,2,NaN
1,2,A - IPC Crime,"Murder (Sec.302/303 IPC/103,104 BNS)",Over Property Dispute,8,0,5,1,NaN
2,3,A - IPC Crime,"Murder (Sec.302/303 IPC/103,104 BNS)",Due to Personal Vendetta or enemity,9,2,6,1,NaN
3,4,A - IPC Crime,"Murder (Sec.302/303 IPC/103,104 BNS)",Due to Sexual jealousy,7,1,4,1,NaN
4,5,A - IPC Crime,"Murder (Sec.302/303 IPC/103,104 BNS)",For dowry by burning,1,0,0,0,NaN

In [103]:
march = march_2025.copy()

# removing garbage column
march = march.drop(columns=['Unnamed: 8'])

#### B: Rename Column

In [104]:
# making columns identical for each month: 

march.columns = [
    'sl_no',
    'crime_head',
    'major_head',
    'minor_head',
    'ytd_current_year',
    'ytd_previous_year',
    'previous_month',
    'current_month'
]

#### Handle Missing Values

In [105]:
march['minor_head'] = march['minor_head'].fillna('ALL / NOT SPECIFIED')

numeric_cols = [
    'ytd_current_year',
    'ytd_previous_year',
    'previous_month',
    'current_month'
]

march[numeric_cols] = march[numeric_cols].fillna(0)

In [106]:
# Month Identifier
march['month'] = '2025-03'

### Loading: APRIL 2025 datafile.csv

In [107]:
april_2025 = pd.read_csv('Raw Datasets/Crime Datasets/CRIME REVIEW FOR YEAR 2025/APRIL 2025 datafile.csv')

april_2025.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 728 entries, 0 to 727
Data columns (total 8 columns):
 #   Column                                                      Non-Null Count  Dtype
---  ------                                                      --------------  -----
 0   Sl. No.                                                     728 non-null    int64
 1   Heads of Crime                                              728 non-null    object
 2   Major Heads                                                 728 non-null    object
 3   Minor Heads                                                 659 non-null    object
 4   During the current year upto the end of month under review  728 non-null    int64
 5   During the corresponding month of previous year             728 non-null    int64
 6   During the previous month                                   728 non-null    int64
 7   During the current month                                    728 non-null    int64
dtypes: int64(5), object(3)
memory usage: 45.6+ KB

In [108]:
april = april_2025.copy()

april.columns = [
    'sl_no',
    'crime_head',
    'major_head',
    'minor_head',
    'ytd_current_year',
    'ytd_previous_year',
    'previous_month',
    'current_month'
]

In [109]:
# Handle Missing Minor Heads
april['minor_head'] = april['minor_head'].fillna('ALL / NOT SPECIFIED')

In [110]:
# Month Identifier
april['month'] = '2025-04'

### Loading: MAY 2025 datafile.csv

In [111]:
may_2025 = pd.read_csv('Raw Datasets/Crime Datasets/CRIME REVIEW FOR YEAR 2025/MAY 2025 datafile.csv')

may_2025.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 732 entries, 0 to 731
Data columns (total 9 columns):
 #   Column                                                      Non-Null Count  Dtype
---  ------                                                      --------------  -----
 0   Sl.No.                                                      732 non-null    int64
 1   Heads of Crime                                              732 non-null    object
 2   Major Heads                                                 732 non-null    object
 3   Minor Heads                                                 681 non-null    object
 4   During the current year upto the end of month under review  727 non-null    float64
 5   During the corresponding month of previous year             727 non-null    float64
 6   During the previous month                                   727 non-null    float64
 7   During the current month                                    726 non-null    float64
 8   Unnamed: 8                                                  3 non-null      float64
dtypes: float64(5), int64(1), object(3)
memory usage: 51.6+ KB

#### Filteration

In [112]:
may = may_2025.copy()

may = may.drop(columns=['Unnamed: 8'])

In [113]:
may.columns = [
    'sl_no',
    'crime_head',
    'major_head',
    'minor_head',
    'ytd_current_year',
    'ytd_previous_year',
    'previous_month',
    'current_month'
]

In [114]:
# missing values:

may['minor_head'] = may['minor_head'].fillna('ALL / NOT SPECIFIED')

numeric_cols = [
    'ytd_current_year',
    'ytd_previous_year',
    'previous_month',
    'current_month'
]

may[numeric_cols] = may[numeric_cols].fillna(0)

In [115]:
# datatype change:
may[numeric_cols] = may[numeric_cols].astype(int)

In [116]:
# month identifier:
may['month'] = '2025-05'

### Loading: JUNE 2025 datafile.csv

In [117]:
june_2025 = pd.read_csv('Raw Datasets/Crime Datasets/CRIME REVIEW FOR YEAR 2025/JUNE 2025 datafile.csv')

june_2025.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 737 entries, 0 to 736
Data columns (total 9 columns):
 #   Column                                                      Non-Null Count  Dtype
---  ------                                                      --------------  -----
 0   Sl.No.                                                      737 non-null    int64
 1   Heads of Crime                                              737 non-null    object
 2   Major Heads                                                 737 non-null    object
 3   Minor Heads                                                 675 non-null    object
 4   During the current year upto the end of month under review  735 non-null    float64
 5   During the corresponding month of previous year             735 non-null    float64
 6   During the previous month                                   735 non-null    float64
 7   During the current month                                    735 non-null    float64
 8   Unnamed: 8                                                  3 non-null      float64
dtypes: float64(5), int64(1), object(3)
memory usage: 51.9+ KB

#### Filteration

In [118]:
# remove column: 
june = june_2025.copy()

june = june.drop(columns=['Unnamed: 8'])

In [119]:
june.columns = [
    'sl_no',
    'crime_head',
    'major_head',
    'minor_head',
    'ytd_current_year',
    'ytd_previous_year',
    'previous_month',
    'current_month'
]

In [120]:
# missing values:
june['minor_head'] = june['minor_head'].fillna('ALL / NOT SPECIFIED')

numeric_cols = [
    'ytd_current_year',
    'ytd_previous_year',
    'previous_month',
    'current_month'
]

june[numeric_cols] = june[numeric_cols].fillna(0)

In [121]:
# Datatype change:
june[numeric_cols] = june[numeric_cols].astype(int)

In [122]:
# MONTH identifier
june['month'] = '2025-06'

### Loading: JULY 2025 datafile.csv

In [123]:
july_2025 = pd.read_csv('Raw Datasets/Crime Datasets/CRIME REVIEW FOR YEAR 2025/JULY 2025 datafile.csv')

july_2025.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 737 entries, 0 to 736
Data columns (total 9 columns):
 #   Column                                                      Non-Null Count  Dtype
---  ------                                                      --------------  -----
 0   Sl.No.                                                      737 non-null    int64
 1   Heads of Crime                                              737 non-null    object
 2   Major Heads                                                 737 non-null    object
 3   Minor Heads                                                 675 non-null    object
 4   During the current year upto the end of month under review  735 non-null    float64
 5   During the corresponding month of previous year             735 non-null    float64
 6   During the previous month                                   735 non-null    float64
 7   During the current month                                    735 non-null    float64
 8   Unnamed: 8                                                  3 non-null      float64
dtypes: float64(5), int64(1), object(3)
memory usage: 51.9+ KB

#### Filteration

In [124]:
july = july_2025.copy()

july = july.drop(columns=['Unnamed: 8'])

In [125]:
july.columns = [
    'sl_no',
    'crime_head',
    'major_head',
    'minor_head',
    'ytd_current_year',
    'ytd_previous_year',
    'previous_month',
    'current_month'
]

In [126]:
# handling missing data:
july['minor_head'] = july['minor_head'].fillna('ALL / NOT SPECIFIED')

numeric_cols = [
    'ytd_current_year',
    'ytd_previous_year',
    'previous_month',
    'current_month'
]

july[numeric_cols] = july[numeric_cols].fillna(0)

In [127]:
# convert Dtype:
july[numeric_cols] = july[numeric_cols].astype(int)

In [128]:
# month identifier
july['month'] = '2025-07'

### Loading: AUGUST 2025 datafile.csv

In [129]:
aug_2025 = pd.read_csv('Raw Datasets/Crime Datasets/CRIME REVIEW FOR YEAR 2025/AUGUST 2025 datafile.csv')

aug_2025.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 764 entries, 0 to 763
Data columns (total 9 columns):
 #   Column                                                      Non-Null Count  Dtype
---  ------                                                      --------------  -----
 0   Sl.No.                                                      764 non-null    int64
 1   Heads of Crime                                              761 non-null    object
 2   Major Heads                                                 764 non-null    object
 3   Minor Heads                                                 691 non-null    object
 4   During the current year upto the end of month under review  763 non-null    float64
 5   During the corresponding month of previous year             762 non-null    float64
 6   During the previous month                                   763 non-null    float64
 7   During the current month                                    763 non-null    float64
 8   Unnamed: 8                                                  3 non-null      float64
dtypes: float64(5), int64(1), object(3)
memory usage: 53.8+ KB

#### Data Filteration

In [130]:
aug = aug_2025.copy()

aug = aug.drop(columns=['Unnamed: 8'])

In [131]:
# renaming the columns:
aug.columns = [
    'sl_no',
    'crime_head',
    'major_head',
    'minor_head',
    'ytd_current_year',
    'ytd_previous_year',
    'previous_month',
    'current_month'
]

In [132]:
# handling missing values:
aug['crime_head'] = aug['crime_head'].fillna('TOTAL / NOT SPECIFIED')

In [133]:
aug['minor_head'] = aug['minor_head'].fillna('ALL / NOT SPECIFIED')

In [134]:
numeric_cols = [
    'ytd_current_year',
    'ytd_previous_year',
    'previous_month',
    'current_month'
]

aug[numeric_cols] = aug[numeric_cols].fillna(0)

In [135]:
# fix Dtype:
aug[numeric_cols] = aug[numeric_cols].astype(int)

In [136]:
# month identifier:
aug['month'] = '2025-08'

### Loading: SEPTEMBER 2025 datafile.csv

In [137]:
sept_2025 = pd.read_csv('Raw Datasets/Crime Datasets/CRIME REVIEW FOR YEAR 2025/SEPT 2025 datafile.csv')
sept_2025.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 767 entries, 0 to 766
Data columns (total 9 columns):
 #   Column                                                      Non-Null Count  Dtype
---  ------                                                      --------------  -----
 0   Sl.No.                                                      767 non-null    int64
 1   Heads Crime                                                 767 non-null    object
 2   Major Heads                                                 767 non-null    object
 3   Minor Heads                                                 715 non-null    object
 4   During the current year upto the end of month under review  764 non-null    float64
 5   During the corresponding month of previous year             764 non-null    float64
 6   During the previous month                                   764 non-null    float64
 7   During the current month                                    764 non-null    float64
 8   Unnamed: 8                                                  3 non-null      float64
dtypes: float64(5), int64(1), object(3)
memory usage: 54.1+ KB

#### Filteration

In [138]:
sept = sept_2025.copy()

sept = sept.drop(columns=['Unnamed: 8'])

In [139]:
#RENAME COLS
sept.columns = [
    'sl_no',
    'crime_head',
    'major_head',
    'minor_head',
    'ytd_current_year',
    'ytd_previous_year',
    'previous_month',
    'current_month'
]

In [140]:
# handling missing values:
sept['minor_head'] = sept['minor_head'].fillna('ALL / NOT SPECIFIED')

# numeric cols filling 
numeric_cols = [
    'ytd_current_year',
    'ytd_previous_year',
    'previous_month',
    'current_month'
]

sept[numeric_cols] = sept[numeric_cols].fillna(0)

In [141]:
sept['minor_head'] = sept['minor_head'].fillna('ALL / NOT SPECIFIED')

In [142]:
# typecast to INT
sept[numeric_cols] = sept[numeric_cols].astype(int)

In [143]:
# month tag
sept['month'] = '2025-09'

### Loading: OCTOBER 2025 datafile.csv

In [144]:
oct_2025 = pd.read_csv('Raw Datasets/Crime Datasets/CRIME REVIEW FOR YEAR 2025/OCTOBER 2025 IPC.csv')
oct_2025.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 15 columns):
 #   Column                                                      Non-Null Count  Dtype
---  ------                                                      --------------  -----
 0   Sl.No.                                                      768 non-null    int64
 1   Heads of Crime                                              768 non-null    object
 2   Major Heads                                                 768 non-null    object
 3   Minor Heads                                                 698 non-null    object
 4   During the current year upto the end of month under review  765 non-null    float64
 5   During the corresponding month of previous year             765 non-null    float64
 6   During the previous month                                   765 non-null    float64
 7   During the current month                                    765 non-null    float64
 8   Unnamed: 8                                                  6 non-null      float64
 9   Unnamed: 9                                                  34 non-null     float64
 10  Unnamed: 10                                                 5 non-null      object
 11  Unnamed: 11                                                 6 non-null      float64
 12  Unnamed: 12                                                 3 non-null      float64
 13  Unnamed: 13                                                 3 non-null      float64
 14  Unnamed: 14                                                 3 non-null      float64
dtypes: float64(10), int64(1), object(4)
memory usage: 90.1+ KB

#### Data Filteration

In [145]:
oct_df = oct_2025.copy()

# Removing All Unnamed Columns
oct_df = oct_df.loc[:, ~oct_df.columns.str.contains('^Unnamed')]

In [146]:
oct_df.columns = [
    'sl_no',
    'crime_head',
    'major_head',
    'minor_head',
    'ytd_current_year',
    'ytd_previous_year',
    'previous_month',
    'current_month'
]

In [147]:
# Handle Missing Text Fields
oct_df['minor_head'] = oct_df['minor_head'].fillna('ALL / NOT SPECIFIED')

In [148]:
# Missing numeric values
numeric_cols = [
    'ytd_current_year',
    'ytd_previous_year',
    'previous_month',
    'current_month'
]

oct_df[numeric_cols] = oct_df[numeric_cols].fillna(0)

In [149]:
# type conversion
oct_df[numeric_cols] = oct_df[numeric_cols].astype(int)

In [150]:
# month identifier
oct_df['month'] = '2025-10'

### Listing Month-Wise Dataframes

In [151]:
print(len(jan.columns))
print(len(feb.columns))
print(len(march.columns))
print(len(april.columns))
print(len(may.columns))
print(len(june.columns))
print(len(july.columns))
print(len(aug.columns))
print(len(sept.columns))
print(len(oct_df.columns))

9
9
9
9
9
9
9
9
9
9

In [155]:
jan.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 729 entries, 0 to 728
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   sl_no              729 non-null    int64
 1   crime_head         729 non-null    object
 2   major_head         729 non-null    object
 3   minor_head         729 non-null    object
 4   ytd_current_year   729 non-null    float64
 5   ytd_previous_year  729 non-null    float64
 6   previous_month     729 non-null    float64
 7   current_month      729 non-null    float64
 8   month              729 non-null    object
dtypes: float64(4), int64(1), object(4)
memory usage: 51.4+ KB

### Concatenating All dataframes

In [156]:
crime_2025_master = pd.concat(
    [jan, feb, march, april, may, june, july, aug, sept, oct_df],
    ignore_index=True
)

In [157]:
crime_2025_master.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7421 entries, 0 to 7420
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   sl_no              7421 non-null   int64
 1   crime_head         7421 non-null   object
 2   major_head         7421 non-null   object
 3   minor_head         7421 non-null   object
 4   ytd_current_year   7421 non-null   float64
 5   ytd_previous_year  7421 non-null   float64
 6   previous_month     7421 non-null   float64
 7   current_month      7421 non-null   float64
 8   month              7421 non-null   object
dtypes: float64(4), int64(1), object(4)
memory usage: 521.9+ KB

In [158]:
crime_2025_master.head()

,sl_no,crime_head,major_head,minor_head,ytd_current_year,ytd_previous_year,previous_month,current_month,month
0,1,A - IPC Crime,"Murder (Sec.302/303 IPC/103,104 BNS)",For gain,4.0,3.0,7.0,4.0,2025-01
1,2,A - IPC Crime,"Murder (Sec.302/303 IPC/103,104 BNS)",Over Property Dispute,2.0,2.0,2.0,2.0,2025-01
2,3,A - IPC Crime,"Murder (Sec.302/303 IPC/103,104 BNS)",Due to Personal Vendetta or enemity,2.0,1.0,2.0,2.0,2025-01
3,4,A - IPC Crime,"Murder (Sec.302/303 IPC/103,104 BNS)",Due to Sexual jealousy,2.0,1.0,2.0,2.0,2025-01
4,5,A - IPC Crime,"Murder (Sec.302/303 IPC/103,104 BNS)",For dowry by burning,0.0,0.0,0.0,0.0,2025-01

### B. Final Sanity Checks

In [159]:
crime_2025_master.info()
crime_2025_master['month'].value_counts().sort_index()
crime_2025_master.isna().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7421 entries, 0 to 7420
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   sl_no              7421 non-null   int64
 1   crime_head         7421 non-null   object
 2   major_head         7421 non-null   object
 3   minor_head         7421 non-null   object
 4   ytd_current_year   7421 non-null   float64
 5   ytd_previous_year  7421 non-null   float64
 6   previous_month     7421 non-null   float64
 7   current_month      7421 non-null   float64
 8   month              7421 non-null   object
dtypes: float64(4), int64(1), object(4)
memory usage: 521.9+ KB

sl_no                0
crime_head           0
major_head           0
minor_head           0
ytd_current_year     0
ytd_previous_year    0
previous_month       0
current_month        0
month                0
dtype: int64

### Fixing Dtype: Global Records

In [ ]:
num_cols = [
    'ytd_current_year',
    'ytd_previous_year',
    'previous_month',
    'current_month'
]
crime_2025_master[num_cols] = crime_2025_master[num_cols].astype(int)

### Implementating Statistics

#### Month-on-Month Change

In [161]:
# cy-py
crime_2025_master['mom_change'] = (
    crime_2025_master['current_month'] -
    crime_2025_master['previous_month']
)

#### Growth Rate %

In [162]:
# Growth = [(cy-py)/py]*100 
crime_2025_master['mom_growth_pct'] = (
    crime_2025_master['mom_change'] /
    crime_2025_master['previous_month'].replace(0, 1)
) * 100

#### Monthly Crime Trend

In [163]:
monthly_trend = (
    crime_2025_master.groupby('month')['current_month'].sum().reset_index()
)

#### Major Head Distribution

In [ ]:
major_head_trend = (
    crime_2025_master.groupby(['month', 'major_head'])['current_month'].sum().reset_index()
)

#### Export Filtered Data:

In [164]:
crime_2025_master.to_csv("FilteredData/Year_2025_Month_Wise/crime_2025_master(combined).csv", index=False)